version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      CONFIG_PATH: ./config.yaml
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movielab
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: