// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/rmntim/movielab/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MovieUpdater is an autogenerated mock type for the MovieUpdater type
type MovieUpdater struct {
	mock.Mock
}

// GetMovieById provides a mock function with given fields: id
func (_m *MovieUpdater) GetMovieById(id int) (*entity.Movie, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieById")
	}

	var r0 *entity.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Movie, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Movie); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Movie)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMovie provides a mock function with given fields: id, movie
func (_m *MovieUpdater) UpdateMovie(id int, movie *entity.Movie) error {
	ret := _m.Called(id, movie)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *entity.Movie) error); ok {
		r0 = rf(id, movie)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMovieUpdater creates a new instance of MovieUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieUpdater {
	mock := &MovieUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
