// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MovieDeleter is an autogenerated mock type for the MovieDeleter type
type MovieDeleter struct {
	mock.Mock
}

// DeleteMovie provides a mock function with given fields: id
func (_m *MovieDeleter) DeleteMovie(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMovieDeleter creates a new instance of MovieDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieDeleter {
	mock := &MovieDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
